### ISSUE TITLE
Restore恢复失败

### ISSUE THREAD

**Issue by nnhy** [NewLifeX/NewLife.XCode#2]
`
17:06:39.349  5 W P 恢复[SampleData2/StardustData]开始，共[18,315]行
17:06:39.349  5 W P 字段[19]：Id,DataId,AppId,Name,Success,StartTime,EndTime,Cost,TraceId,SpanId,ParentId,Tag,Error,CreateUser,CreateUserID,CreateIP,CreateTime,ClientId,ItemId
17:06:39.349  5 W P 类型[19]：Int64,Int64,Int32,String,SByte,Int64,Int64,Int32,String,String,String,String,String,String,Int32,String,DateTime,String,Int32
17:06:39.354  5 W P NewLife.XException: 安全需要，不允许读取超大变长数组 2,841>2,048
   at NewLife.Serialization.BinaryGeneral.ReadBytes(Int32 count)
   at NewLife.Serialization.BinaryGeneral.ReadString()
   at NewLife.Serialization.BinaryGeneral.TryRead(Type type, Object& value)
   at NewLife.Serialization.Binary.TryRead(Type type, Object& value)
   at NewLife.Serialization.Binary.Read(Type type)
   at NewLife.Data.DbTable.ReadData(Binary bn, Int32 rows)
   at XCode.DataAccessLayer.DbPackage.Restore(Stream stream, IDataTable table)
   at XCode.DataAccessLayer.DbPackage.<>c__DisplayClass25_0.<Restore>b__0(Stream s)
   at System.IO.PathHelper.OpenRead(FileInfo file, Boolean compressed, Action`1 func)
   at XCode.DataAccessLayer.DbPackage.Restore(String file, IDataTable table, Boolean setSchema)
   at XCode.DataAccessLayer.DAL.Restore(String file, IDataTable table, Boolean setSchema)
   at NewLife.Cube.EntityController`1.Restore()

`

**Comment by nnhy** [comment]
已查明，该错误起因是二进制序列化内部的安全保护屏障设置过低，导致读取超大数据（>2048字节）时报错。
星尘SampleData2表恰巧有个大文本字段，其中保存有很大的字符串内容，因此恢复失败。

**Comment by nnhy** [comment]
https://github.com/NewLifeX/NewLife.XCode/commit/e29ccdb7e2d795f87781c95c715700ed32fda57a

fix #2
